# frozen_string_literal: true

require "fileutils"
require "json"
require "rake/testtask"
require "rbconfig"

WORKSPACE = File.expand_path("../..", __dir__)

desc "Build the native extension through Cargo and copy it into lib/trellis/"
task :compile do
  # rb-sys's build script asks this Ruby for its headers and link flags.
  sh({ "RUBY" => RbConfig.ruby },
     "cargo", "build", "-p", "trellis_ruby", "--features", "ruby", chdir: WORKSPACE)

  metadata = JSON.parse(IO.popen(%w[cargo metadata --format-version 1 --no-deps],
                                 chdir: WORKSPACE, &:read))
  built = File.join(metadata.fetch("target_directory"), "debug",
                    "libtrellis_ruby.#{RbConfig::CONFIG.fetch('SOEXT')}")
  FileUtils.cp(built, File.join(__dir__, "lib", "trellis",
                                "trellis_ruby.#{RbConfig::CONFIG.fetch('DLEXT')}"))
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = true
end
task test: :compile

task default: :test
