-- Issue #73 / ADR-0007: `transform_definitions.target_table` is now persisted
-- fully-qualified (`schema.table`), resolved once at definition-acceptance
-- time exactly like `source_table` was in issue #72. `column_status.transform_table`
-- (V21__column_quarantine.sql) deliberately does *not* follow it to qualified
-- form: it's one key in a self-consistent, bare-keyed bookkeeping subsystem
-- (`column_status`, `column_deaths`, `column_failures`, `column_pause_cascades`
-- — see `staging::quarantine`'s module doc comment) seeded from the bare
-- transform name a `Trellis` API caller supplies or `def.def.target` (always
-- bare — the grammar has no qualified-target syntax yet, issue #76) already
-- has. Keeping it bare also keeps `docs/decisions/0003`'s `transform.column`
-- addressing scheme (`app::QuarantineTarget::parse`, which splits an address
-- on its first `.`) working: a qualified transform name here would misparse
-- as a column address the moment a target table lived outside the default
-- schema. See `defs::catalog::column_dependents`'s doc comment for the full
-- rationale.
--
-- `column_status_transform_table_fkey` assumed `target_table` stayed bare
-- too, and can no longer hold now that it doesn't: a bare
-- `column_status.transform_table` never equals a now-qualified
-- `transform_definitions.target_table`, so every column-pause insert
-- (`staging::quarantine::pause_column`/`cascade_pause`) would fail with a
-- foreign-key violation. There is no schema-level fix that keeps both sides
-- as they are and still enforces the reference: pointing this FK at a
-- qualified column instead would mean either qualifying
-- `column_status.transform_table` too (reopening the exact addressing-scheme
-- collision above) or adding a generated bare-suffix column purely to hang a
-- constraint off of. Dropped instead — referential integrity between the two
-- becomes an invariant this code maintains (every write goes through
-- `staging::quarantine`, which only ever pauses a column of a definition
-- `catalog::column_dependents`/`transforms_for_source` just read back from
-- the catalog), not one the database enforces, the same trust level several
-- of this crate's other cross-table string keys already operate at (e.g.
-- `poison.src_table`, never foreign-keyed to `source_table_versions` either).
alter table column_status drop constraint column_status_transform_table_fkey;
