-- Reviewer follow-up to issue #73 / ADR-0007 (see
-- `CatalogError::TargetTableSuffixCollision`'s own doc comment in
-- `trellis/src/defs/catalog.rs`): `create_definition_inner`'s app-level
-- pre-check rejects a new definition whose bare target-table suffix
-- (`split_part(target_table, '.', 2)`) collides with a *different* qualified
-- target some other live definition already uses -- but that check only ever
-- sees its own transaction's snapshot of `transform_definitions`. Two
-- concurrent `create_definition` calls resolving different-schema targets
-- for the same bare suffix (e.g. `public.foo` and `custom.foo`, most
-- plausibly from `Config::target_schema` changing between deploys) can each
-- pass the pre-check against a snapshot that doesn't yet see the other's
-- uncommitted insert, and both commit -- nothing in the database itself
-- enforced the bare-suffix invariant, only the application-level check did.
--
-- This expression unique index is the real, DB-level guard that closes that
-- race, the same way `target_table`'s own plain `unique` constraint
-- (`transform_definitions_target_table_key`, `V2__transform_catalog.sql`)
-- already makes exact-qualified-name collisions impossible with zero race
-- window -- extended here to the bare suffix every `split_part`-keyed read
-- site (`definition_by_target`, `dependents_of`, `app.rs`'s status/
-- quarantine polls, `generative`'s `unsettled_definitions`) assumes is
-- globally unique. One of the two concurrent inserts above now always loses
-- to this index rather than both quietly committing.
--
-- `create_definition_inner` catches that rare insert-time failure (matched
-- by this index's name) and translates it back into the same
-- `CatalogError::TargetTableSuffixCollision` the pre-check raises in the
-- common, non-racing case, so a caller never sees a raw constraint-violation
-- error for this invariant -- the pre-check stays the primary path (it can
-- report the colliding qualified name; a unique-violation on a `split_part`
-- expression index cannot), this index is the backstop for the race the
-- pre-check's own transaction snapshot cannot see.
create unique index if not exists transform_definitions_target_suffix_idx
    on transform_definitions (split_part(target_table, '.', 2));
