-- Issue #74 / ADR-0007: `schema_nodes`/`schema_edges` now key on
-- fully-qualified `schema.table` identity, closing the last gap #72/#73/#76
-- deliberately left open (see the `TODO(#74)`s at
-- `create_definition_inner`'s node/edge resolution in
-- `trellis/src/defs/catalog.rs`). Before this, `public.posts` and
-- `archive.posts` collided into the same bare `schema_nodes.table_name`
-- row, sharing one set of edges/quarantine-relevant state despite naming
-- two different physical tables — exactly the ambiguity this whole epic
-- exists to close.
--
-- ADR-0007's own "Consequences" section calls for a *data* migration:
-- canonicalizing each existing `table_name` row in place by resolving it
-- against the schema it was created under. This migration does not attempt
-- that. Trellis has no production deployment yet — `Cargo.toml` is still
-- `0.1.0`, there are no tags/releases, and ADR-0007 itself is still
-- `status: proposed` — and #72/#73 already set this epic's precedent under
-- that same constraint: #72 shipped with *zero* migration despite changing
-- what `source_table_versions`/`transform_definitions` persist, trusting
-- that no live row needed reconciling; V22/V23 (#73) only ever adjust
-- constraints, never attempt to resolve a hypothetical pre-existing bare
-- value against a live catalog from inside a migration. That's also the
-- structurally sound choice, not just the convenient one: real
-- canonicalization needs `search_path`-aware, per-row resolution logic
-- identical to `resolve_source_schema_in_txn`/`create_definition_inner`'s
-- qualification — logic that belongs in Rust against a live connection, not
-- duplicated in a one-shot SQL migration that would still be guessing at
-- the right search_path for a row with no other recorded context.
--
-- So, following that precedent: any pre-existing `schema_nodes`/
-- `schema_edges` rows are bare and thus definitionally stale under the new
-- keying — cleared outright rather than half-canonicalized. This is safe
-- *only* because there is no production deployment to lose state from:
-- `resolve_node_in_txn`/`persist_edge_in_txn` are called exclusively from
-- `create_definition_inner`/`create_relationship`, i.e. only when a
-- *new* definition/relationship is accepted — there is no startup/repair
-- pass anywhere in this crate that walks already-installed
-- `transform_definitions`/`relationship_definitions` rows to rebuild
-- `schema_nodes`/`schema_edges` for them. A database with live,
-- already-installed definitions would have those definitions' edges
-- truncated here and never regenerated — `transforms_for_source`/
-- `dependents_of` (read-only; `staging/apply.rs`'s live-CDC dispatch path)
-- would then silently stop finding them, with no error. Do not reuse this
-- migration as precedent once real deployments exist; at that point this
-- needs to become an actual per-row canonicalization (or a repair pass
-- gets added first). `schema_edges` truncates first (nothing cascades:
-- neither table declares `on delete cascade`, so a bare `truncate
-- schema_nodes` alone would fail on `schema_edges`' `not null references
-- schema_nodes (id)` foreign keys).
truncate table schema_edges, schema_nodes restart identity;

-- `table_name`'s uniqueness constraint needs no change here, unlike #73's
-- `target_table`: that column's uniqueness spans a single column
-- (`schema_nodes_table_name_key`, the plain `unique` `V14__schema_nodes.sql`
-- already declares), so once every row holds its qualified value, "the
-- qualified value is unique" is exactly what that constraint already
-- enforces — no cross-column bare-suffix ambiguity like
-- `transform_definitions.target_table` had (that one needed
-- `transform_definitions_target_suffix_idx`, a *separate* expression index,
-- precisely because two different qualified spellings can still share a
-- bare suffix; `schema_nodes.table_name` has no such second, coarser
-- identity anything reads it by).
