-- Completion tracking for issue #11's 1-1 apply ∪ mark-drained (stage 05).
-- See docs/staging-and-claiming/05-apply-and-exactly-once-deltas.md,
-- "Apply ∪ mark-drained are one transaction".
--
-- `drained_mask` is a dedicated column, deliberately not a repurposing of
-- the vestigial `bucket_mask` from `V3__staging_ring.sql` (which stays
-- unused — nothing in this crate reads or writes it, and giving it a real
-- meaning now would tangle this migration's history with a column an
-- earlier stage never finished defining). It ORs in the bit for every
-- bucket a completed claim's [`engine::staging::apply::apply_and_mark_drained`]
-- has drained; the batch is fully drained exactly when it equals
-- `(1 << bucket_count) - 1` — see that function's completion statement.
alter table segments add column drained_mask bigint not null default 0;
